# Generated by Django 4.1.2 on 2022-10-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["stage_name", "albums"]},
        ),
    ]
