# Generated by Django 4.1.2 on 2022-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_alter_artist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["stage_name"]},
        ),
    ]
