# Generated by Django 4.1.2 on 2022-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_alter_album_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
