# Generated by Django 4.1.2 on 2022-10-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0006_alter_album_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                ("image", models.ImageField(upload_to="media/images")),
                ("audio", models.FileField(upload_to="media/audios")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="albums.album",
                    ),
                ),
            ],
            options={
                "db_table": "songs",
            },
        ),
    ]
