# Generated by Django 4.1.2 on 2022-10-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0007_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio",
            field=models.FileField(upload_to="static/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(upload_to="static/"),
        ),
    ]
