# Generated by Django 4.1.2 on 2022-11-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0008_alter_song_audio_alter_song_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="artist",
        ),
    ]
