# Generated by Django 4.1.2 on 2022-11-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0004_alter_artist_managers_remove_artist_id_and_more"),
        ("albums", "0009_remove_album_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="artists.artist",
            ),
        ),
    ]
