# Generated by Django 4.1.2 on 2022-11-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extendeduser",
            options={},
        ),
        migrations.AlterModelTable(
            name="extendeduser",
            table="users",
        ),
    ]
