# Generated by Django 4.1.2 on 2022-11-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_extendeduser_options_alter_extendeduser_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendeduser",
            name="bio",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
