# Generated by Django 4.1.2 on 2022-11-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_extendeduser_repeated_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendeduser",
            name="repeated_password",
        ),
    ]
