# Generated by Django 4.1.2 on 2022-11-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_extendeduser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendeduser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
