# Generated by Django 4.1.2 on 2022-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_extendeduser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendeduser",
            name="email",
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
